___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [6]:
zeros_array = np.zeros(10)
print("1. Array of 10 zeros:")
print(zeros_array)
print()

1. Array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]



#### Create an array of 10 ones

In [7]:
ones_array = np.ones(10)
print("2. Array of 10 ones:")
print(ones_array)
print()

2. Array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]



#### Create an array of 10 fives

In [8]:
fives_array = np.ones(10) * 5
print("3. Array of 10 fives:")
print(fives_array)
print()

3. Array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]



#### Create an array of the integers from 10 to 50

In [9]:
range_array = np.arange(10, 51)
print("4. Array of integers from 10 to 50:")
print(range_array)
print()

4. Array of integers from 10 to 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]



#### Create an array of all the even integers from 10 to 50

In [10]:
even_array = np.arange(10, 51, 2)
print("5. Array of even integers from 10 to 50:")
print(even_array)
print()

5. Array of even integers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]



#### Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("6. 3x3 matrix with values 0 to 8:")
print(matrix_3x3)
print()

6. 3x3 matrix with values 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]



#### Create a 3x3 identity matrix

In [12]:
identity_matrix = np.eye(3)
print("7. 3x3 identity matrix:")
print(identity_matrix)
print()

7. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



#### Use NumPy to generate a random number between 0 and 1

In [13]:
random_number = np.random.rand(1)
print("8. Random number between 0 and 1:")
print(random_number)
print()

8. Random number between 0 and 1:
[0.79856505]



#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [14]:
random_normal = np.random.randn(25)
print("9. Array of 25 random numbers from standard normal distribution:")
print(random_normal)
print()

9. Array of 25 random numbers from standard normal distribution:
[ 0.09500377  0.56800786 -0.33277334 -0.22777237 -0.09617904  0.74894558
 -0.86520188  1.3057524  -0.16546014 -0.89259296  0.21269026  0.07634713
  0.01207277  1.76591762 -1.95430911 -1.57974449  0.57336259  0.14641287
 -1.42268287 -1.29938633 -0.53171755  0.99545544 -1.6465533   0.65765701
 -0.44794037]



#### Create the following matrix:

In [15]:
decimal_matrix = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print("10. 10x10 matrix with values 0.01 to 1.00:")
print(decimal_matrix)
print()

10. 10x10 matrix with values 0.01 to 1.00:
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]



#### Create an array of 20 linearly spaced points between 0 and 1:

In [16]:
linspace_array = np.linspace(0, 1, 20)
print("11. Array of 20 linearly spaced points between 0 and 1:")
print(linspace_array)
print()

11. Array of 20 linearly spaced points between 0 and 1:
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]



## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [17]:
mat = np.arange(1, 26).reshape(5, 5)
print("Original matrix:")
print(mat)
print()

Original matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]



In [18]:
result1 = mat[2:, 1:]
print("Indexing 1 - mat[2:, 1:]:")
print(result1)
print()


Indexing 1 - mat[2:, 1:]:
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]



array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [20]:
result2 = mat[3, 4]
print(result2)
print()

20



20

In [22]:
result3 = mat[0:3, 1:2]
print("Indexing 3 - mat[0:3, 1:2]:")
print(result3)
print()

Indexing 3 - mat[0:3, 1:2]:
[[ 2]
 [ 7]
 [12]]



array([[ 2],
       [ 7],
       [12]])

In [23]:
result4 = mat[4, :]
# Alternative: mat[-1, :] or mat[4]
print("Indexing 4 - mat[4, :] (last row):")
print(result4)
print()

Indexing 4 - mat[4, :] (last row):
[21 22 23 24 25]



array([21, 22, 23, 24, 25])

In [24]:
result5 = mat[3:, :]
# Alternative: mat[-2:, :] or mat[3:]
print("Indexing 5 - mat[3:, :] (last two rows):")
print(result5)
print()

Indexing 5 - mat[3:, :] (last two rows):
[[16 17 18 19 20]
 [21 22 23 24 25]]



array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [25]:
total_sum = mat.sum()
print("Sum of all values in mat:")
print(total_sum)
print()

Sum of all values in mat:
325



#### Get the standard deviation of the values in mat

In [26]:
std_dev = mat.std()
print("Standard deviation of values in mat:")
print(std_dev)
print()

Standard deviation of values in mat:
7.211102550927978



#### Get the sum of all the columns in mat

In [27]:
column_sums = mat.sum(axis=0)
print("Sum of all columns in mat:")
print(column_sums)
print()

Sum of all columns in mat:
[55 60 65 70 75]



# Great Job!